# Generated by Django 3.0.7 on 2021-02-03 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default=False, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the form of +919999999999.', regex='^[6-9]\\d{9}$')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of opt_sent')),
                ('validated', models.BooleanField(default=False, help_text='if it is true, that means user have validate opt correctly in seconds')),
            ],
        ),
    ]
