# Generated by Django 3.0.7 on 2021-02-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='otp',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
